### ISSUE TITLE
No changed

### ISSUE THREAD

**Issue by switch0** [rekby/fsextender#21]
fsextender /dev/mapper/volgrp01-optlv
2017/01/11 16:01:12 Can't get disk size: /dev/loop0
2017/01/11 16:01:12 Can't get disk size: /dev/loop1
2017/01/11 16:01:12 Can't get disk size: /dev/loop2
2017/01/11 16:01:12 Can't get disk size: /dev/loop3
2017/01/11 16:01:12 Can't get disk size: /dev/loop4
2017/01/11 16:01:12 Can't get disk size: /dev/loop5
2017/01/11 16:01:12 Can't get disk size: /dev/loop6
2017/01/11 16:01:12 Can't get disk size: /dev/loop7
2017/01/11 16:01:12 I can't work with non msdos/gpt table partition. TODO.: /dev/loop2,
2017/01/11 16:01:12 I can't work with non msdos/gpt table partition. TODO.: /dev/loop5,
2017/01/11 16:01:12 I can't work with non msdos/gpt table partition. TODO.: /dev/loop7,
2017/01/11 16:01:12 I can't work with non msdos/gpt table partition. TODO.: /dev/loop0,
2017/01/11 16:01:12 I can't work with non msdos/gpt table partition. TODO.: /dev/loop1,
2017/01/11 16:01:12 I can't work with non msdos/gpt table partition. TODO.: /dev/loop3,
2017/01/11 16:01:12 I can't work with non msdos/gpt table partition. TODO.: /dev/loop4,
2017/01/11 16:01:12 I can't work with non msdos/gpt table partition. TODO.: /dev/loop6,
0: [Type: type_PARTITION, Path: /dev/sda2, Size: 899.7GiB (+50.0GiB), Child: 1, PartNum=2] May need reboot
1: [Type: type_LVM_PV, Path: /dev/sda2, Size: 899.7GiB (+50.0GiB), Child: 4, ExtentSize: 64.0MiB]
2: [Type: type_SKIP, Path: /dev/sda3, Size: 0.0B (+50.0GiB), Child: 3, Reason: Partition layout optimization. Partition number may be wrong becouse it optimize too.]
3: [Type: type_SKIP, Path: /dev/sda3, Size: 0.0B (+50.0GiB), Child: 4, Reason: Partition layout optimization. Partition number may be wrong becouse it optimize too.]
4: [Type: type_LVM_GROUP, Path: volgrp01, Size: 899.7GiB (+100.0GiB), Child: 5, ExtentSize: 64.0MiB]
5: [Type: type_LVM_LV, Path: volgrp01/optlv, Size: 875.7GiB (+100.0GiB), Child: 6]
6: [Type: type_FS, Path: /dev/dm-3, Size: 875.7GiB (+100.0GiB), Child: -1, FS: ext3]

**Comment by rekby** [comment]
try add key --do:

fsextender /dev/mapper/volgrp01-optlv --do


Default fsextender only print extend plan - for you can verify it, becouse extend partition/file system hard to undo. It really work only with key --do.
