### ISSUE TITLE
xfs_growfs requires mount-point as a target in RHEL 8

### ISSUE THREAD

**Issue by fluggelgleckheimlen** [rekby/fsextender#22]
На CentOS/RHEL 8 не работает расширение файловой системы, так как xfs_growfs теперь нужна точка монтирования, а не блочное устройство:
```
Filesystem doesn't extend. Log of resize:
stderr: xfs_growfs: /dev/mapper/rhel-root is not a mounted XFS filesystem
```
Расширение PV, VG и LV проходит успешно и достаточно запустить `xfs_growfs /` после выполнения fsextender.

**Comment by fluggelgleckheimlen** [comment]
Тут пишут и про седьмую ветку, но возможно только с ядром от Oracle:
https://serverfault.com/a/986820

**Comment by rekby** [comment]
Спасибо за сообщение об ошибке.

В документации к xfs_growfs всегда было написано, что в качестве параметра должен быть путь к точке монтирования. При этом старые версии принимали в качестве параметра и адрес блочного устройства и точку монтирования. Поэтому на старых версиях всё работало и ошибка не была замечена.

В новых версиях похоже что утилита стала работать в соответствие с описанием и ошибка проявилась.

Попробуйте версию 0.1.6
https://github.com/rekby/fsextender/releases/tag/v0.1.6
